version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3030:3030"
    depends_on:
      - db
    working_dir: "/myapp"
    command: "rails s -p 3030 -b 0.0.0.0"